keycloak:
  auth-server-url: http://keycloak:8080/
  realm: EpisodeSwitcher
  resource: episode-switcher
  bearer-only: true
server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null